### PR TITLE
update w/ index and separate js, css

### PR DESCRIPTION
**Pull request by jahoops**
I've never really tried this before, but I did a "fork" of your clock and made some changes, and so now I think this pull request allows you to review my changes and integrate them if you want.

Remember to run http-server in the terminal.  You just type:
http-server

Then you can click one of the links to open your browser, or if you have Chrome debugging set up you can click on the bug icon in vscode and it will open Chrome to the right place.

To open the terminal press CTRL and ` (upper left to the left of the 1 key)

### CODE REVIEW

**Comment by jahoops** [comment]
this is a pull request I guess

**Comment by KalliHooper** [comment]
Does it automatically update the files on github if I open and work on them?

**Comment by jahoops** [comment]
If you push your changes.  To make things a lot more confusing, remember that you ALWAYS have a local "repository" on your computer, and so when you do the obvious thing in Visual Studio Code and save them, they are only saved locally.  You have to then specifically "Push" the changes (again) to the actual GitHub repository.

First you have to click on the nonsensical "source control" icon, that looks like ... I dunno, sort of like a Y.

Then it should show changes, and when you click the check it saves the changes -- on your computer.  Super useful, eh?  The magic is the three dots up there next to Source Control and the check mark.  If you click that, you can select Push, not that any indication is given of what it does, why, if it is important, etc.

95% of programming is trying to figure out awful interfaces and libraries of code.

I don't see my changes on GitHub, so I don't think they were merged.  Try changing mine that I invited you to.  It makes sense that everyone should guess, or spend hours reading mostly old garbage that is now wrong and no longer applies, until they get lucky and figure out how to do THE MOST BASIC thing imaginable.

**Comment by jahoops** [comment]
No, you have to push the changes, look at the answer to this question:

https://stackoverflow.com/questions/46382883/shortcut-to-push-code-to-git-in-vscode

**Pull request merged**
